<a href="https://colab.research.google.com/github/edogriba/SMBUD-2024/blob/main/DataWrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Systems and Methods for Big Data Project 2024

Edoardo S. Gribaldo

In [56]:
import pandas as pd
import numpy as np

In [57]:
df = pd.read_csv('Airline_review.csv')
df.head()

,Unnamed: 0,Airline Name,Overall_Rating,Review_Title,Review Date,Verified,Review,Aircraft,Type Of Traveller,Seat Type,Route,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Inflight Entertainment,Wifi & Connectivity,Value For Money,Recommended
0,0,AB Aviation,9,"""pretty decent airline""",11th November 2019,True,Moroni to Moheli. Turned out to be a pretty ...,NaN,Solo Leisure,Economy Class,Moroni to Moheli,November 2019,4.0,5.0,4.0,4.0,NaN,NaN,3.0,yes
1,1,AB Aviation,1,"""Not a good airline""",25th June 2019,True,Moroni to Anjouan. It is a very small airline...,E120,Solo Leisure,Economy Class,Moroni to Anjouan,June 2019,2.0,2.0,1.0,1.0,NaN,NaN,2.0,no
2,2,AB Aviation,1,"""flight was fortunately short""",25th June 2019,True,Anjouan to Dzaoudzi. A very small airline an...,Embraer E120,Solo Leisure,Economy Class,Anjouan to Dzaoudzi,June 2019,2.0,1.0,1.0,1.0,NaN,NaN,2.0,no
3,3,Adria Airways,1,"""I will never fly again with Adria""",28th September 2019,False,Please do a favor yourself and do not fly wi...,NaN,Solo Leisure,Economy Class,Frankfurt to Pristina,September 2019,1.0,1.0,NaN,1.0,NaN,NaN,1.0,no
4,4,Adria Airways,1,"""it ruined our last days of holidays""",24th September 2019,True,Do not book a flight with this airline! My fr...,NaN,Couple Leisure,Economy Class,Sofia to Amsterdam via Ljubljana,September 2019,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no

In [58]:
df.dtypes

Unnamed: 0                  int64
Airline Name               object
Overall_Rating             object
Review_Title               object
Review Date                object
Verified                     bool
Review                     object
Aircraft                   object
Type Of Traveller          object
Seat Type                  object
Route                      object
Date Flown                 object
Seat Comfort              float64
Cabin Staff Service       float64
Food & Beverages          float64
Ground Service            float64
Inflight Entertainment    float64
Wifi & Connectivity       float64
Value For Money           float64
Recommended                object
dtype: object

In [59]:
t = df.columns
for e in t:
  print(df[e].unique())

[    0     1     2 ... 23168 23169 23170]
['AB Aviation' 'Adria Airways' 'Aegean Airlines' 'Aer Lingus' 'Aero VIP'
 'Aerocaribbean' 'Aeroflot Russian Airlines' 'AeroItalia'
 'Aerolineas Argentinas' 'Aeromar' 'Aeromexico' 'Aerosur'
 'Africa World Airlines' 'Afriqiyah Airways' 'Aigle Azur' 'Air Algerie'
 'Air Antilles' 'Air Arabia' 'Air Astana' 'Air Austral' 'Air Bagan'
 'Air Berlin' 'Air Botswana' 'Air Burkina' 'Air Busan' 'Air Cairo'
 'Air Canada' 'Air Canada rouge' 'Air Caraibes' 'Air China' 'Air Corsica'
 'Air Costa' "Air Cote d'Ivoire" 'Air Djibouti' 'Air Dolomiti'
 'Air Europa' 'Air France' 'Air Greenland' 'Air Iceland Connect'
 'Air India' 'Air India Express' 'Air Italy' 'Air Juan' 'Air KBZ'
 'Air Koryo' 'Air Labrador' 'Air Macau' 'Air Madagascar' 'Air Malawi'
 'Air Malta' 'Air Mauritius' 'Air Mediterranee' 'Air Memphis'
 'Air Moldova' 'Air Namibia' 'Air New Zealand' 'Air Niugini'
 "Air North Yukon's Airline" 'Air Nostrum' 'Air Panama' 'Air Pegasus'
 'Air Rarotonga' 'Air Serbia' 'Air Seychelles' 'Air Tahiti Nui'
 'Air Tanzania' 'Air Transat' 'Air Zimbabwe' 'AirAsia' 'AirAsia India'
 'AirAsia Philippines' 'AirAsia X' 'AirAsia Zest' 'airBaltic' 'Aircalin'
 'Airlink' 'Airnorth' 'AirSWIFT' 'Akasa Air' 'Alaska Airlines' 'Alitalia'
 'Allegiant Air' 'Alliance Air' 'Alliance Airlines' 'Amaszonas'
 'American Airlines' 'American Eagle' 'ANA All Nippon Airways'
 'AnadoluJet' 'Andes Líneas Aéreas' 'Ariana Afghan Airlines' 'Arik Air'
 'Arkefly' 'Armenia Air Company' 'Asiana Airlines' 'ASKY Airlines'
 'ATA Airlines' 'Atlantic Airways' 'Auric Air' 'Aurigny Air'
 'Austrian Airlines' 'Avelo Airlines' 'Avianca' 'Avior Airlines'
 'Azerbaijan Airlines' 'Azur Air Germany' 'BA CityFlyer' 'Badr Airlines'
 'Bahamasair' 'Bamboo Airways' 'Bangkok Airways' 'Bassaka Air' 'Batik Air'
 'Beijing Capital Airlines' 'Belavia' 'Berjaya Air' 'Bhutan Airlines'
 'Binter Canarias' 'Blue Air' 'Blue Islands' 'Blue Panorama Airlines'
 'Blue1' 'Bluebird Airways' 'bmi Regional' 'BoraJet' 'Boutique Air'
 'Breeze Airways' 'British Airways' 'Brussels Airlines' 'Buddha Air'
 'Bulgaria Air' 'Buta Airways' 'Camair-Co' 'Cambodia Airways'
 'Cambodia Bayon Airlines' 'Canadian North' 'Canaryfly' 'Cape Air'
 'Caribbean Airlines' 'Carpatair' 'Cathay Dragon' 'Cathay Pacific Airways'
 'Cayman Airways' 'Cebu Pacific' 'CemAir' 'Central Mountain Air'
 'China Airlines' 'China Eastern Airlines' 'China Southern Airlines'
 'China United Airlines' 'Citilink' 'CityJet' 'Coastal Aviation' 'Cobalt'
 'Comair' 'Condor Airlines' 'Conviasa' 'Copa Airlines' 'Corendon Airlines'
 'Corsair' 'Croatia Airlines' 'CSA Czech Airlines' 'Cubana Airlines'
 'Cyprus Airways' 'Delta Air Lines' 'Dimonim Air' 'Dniproavia' 'Dragonair'
 'Druk Air' 'Dynamic International Airways' 'Eastern Airlines'
 'Eastern Airways' 'Easyfly' 'easyJet' 'Edelweiss Air' 'Egyptair'
 'El Al Israel Airlines' 'Ellinair' 'Emirates' 'Eritrean Airlines'
 'Ernest Airlines' 'Estonian Air' 'Eswatini Air' 'Ethiopian Airlines'
 'Etihad Airways' 'euroAtlantic Airways' 'Europe Airpost' 'Eurowings'
 'EVA Air' 'Evelop Airlines' 'EWA Air' 'Ravn Alaska' 'fastjet'
 'Felix Airways' 'Fiji Airways' 'Finnair' 'Firefly' 'Flair Airlines'
 'Fly540.com' 'flyadeal' 'FlyArystan' 'flybe' 'flydubai' 'Flynas' 'FLYONE'
 'FlySafair' 'FMI Air' 'French Bee' 'Frontier Airlines' 'Garuda Indonesia'
 'Georgian Airways' 'Germania Airline' 'Germanwings' 'Go First' 'GoAir'
 'Golden Myanmar Airlines' 'Grand Cru Airlines' 'Greater Bay Airlines'
 'Gulf Air' 'Hainan Airlines' 'Hawaiian Airlines' 'Henan Airlines'
 'Hi Fly' 'Himalaya Airlines' 'HiSky' 'Hong Kong Airlines' 'HOP!'
 'Horizon Air' 'Hunnu Air' 'Iberia' 'Iberia Express' 'Iberojet'
 'Icelandair' 'Insel Air' 'Intercaribbean Airways' 'Interjet' 'InterSky'
 'Iran Air' 'Iraqi Airways' 'Israir Airlines' 'ITA Airways'
 'Japan Airlines' 'Jazeera Airways' 'Jazz' 'JC International Airlines'
 'Jeju Air' 'Jet Airways' 'Jet2.com' 'Jetairfly' 'Jetblue Airways'
 'JetSmart' 'Jetstar Airways' 'Jetstar Asia' 'Jetstar Japan'
 'Jetstar Pacific' 'JetsuiteX' 'Jin Air' 'Joon' 'Jordan Aviation'
 'Kam Air' 'Kan Air' 'Karthago Airlines' 'KD Air' 'Kenya Airways'
 'KLM Royal Dutch Airlines' 'Korean Air' 'Kulula' 'Kuwait Airways'
 'La Compagnie' 'LAN Airlines' 'LAN Colombia' 'LAN Peru' 'Lao Airlines'
 'LATAM Airlines' 'Laudamotion' 'LC Perú' 'Level' 'LIAT' 'Libyan Airlines'
 'Lion Air' 'Loch Lomond Seaplanes' 'Loganair' 'LOT Polish Airlines'
 'Lubeck Air' 'Lucky Air' 'Lufthansa' 'Luxair' 'Lynx Air' 'Mack Air'
 'Madagasikara Airways' 'Mahan Air' 'Malawian Airlines'
 'Malaysia Airlines' 'Maldivian' 'Malindo Air' 'Mandarin Airlines'
 'Mann Yadanarpon Airlines' 'Manta Air' 'Martinair' 'Mauritania Airlines'
 'Maya Island Air' 'MAYAir' 'MEGA Maldives Airlines' 'Meridiana'
 'Mihin Lanka' 'Mokulele Airlines' 'Moldavian Airlines' 'Monarch Airlines'
 'Montenegro Airlines' 'Motor Sich Airlines' 'Myanmar Airways'
 'Myanmar National Airlines' 'NAM Air' 'Nature Air' 'Nauru Airlines'
 'Nepal Airlines' 'NextJet' 'NIKI' 'Nile Air' 'Nok Air' 'NokScoot'
 'Nordavia' 'Nordic Regional Airlines' 'Nordica' 'NordStar'
 'Nordwind Airlines' 'Norse Atlantic Airways' 'Norwegian' 'Nouvelair'
 'Novair' 'Novoair' 'Okay Airways' 'Olympic Air' 'Oman Air'
 'Omni Air International' 'Onur Air' 'Openskies' 'Pacific Airlines'
 'PAL Express' 'Pan Pacific Airlines' 'Passion Air' 'PAWA Dominicana'
 'Peach Aviation' 'Pegasus Airlines' 'PenAir' 'Peruvian Airlines'
 'Petroleum Air Services' 'Philippine Airlines' 'Phuket Air' 'PLAY'
 'Pobeda Airlines' 'Porter Airlines' 'Primera Air' 'Privilege Style'
 'Qantas Airways' 'QantasLink' 'Qatar Airways' 'Qazaq Air'
 'Red Wings Airlines' 'Regent Airways' 'Regional Express' 'Rex Airlines'
 'Rhein-Neckar Air' 'Rossiya Airlines' 'Royal Air Maroc'
 'Royal Brunei Airlines' 'Royal Jordanian Airlines' 'Rwandair' 'Ryanair'
 'S7 Siberia Airlines' 'SA Express' 'Safarilink' 'Safi Airways'
 'Salam Air' 'Sansa Airlines' 'SATA Air Azores' 'SATENA'
 'Saudi Arabian Airlines' 'SCAT Airlines' 'Scoot' 'Seaborne Airlines'
 'SereneAir' 'Shaheen Air' 'Shandong Airlines' 'Shanghai Airlines'
 'Shenzhen Airlines' 'Sichuan Airlines' 'SilkAir' 'Silver Airways'
 'Singapore Airlines' 'Sky Airline' 'Sky Express Airlines' 'Skybus'
 'Skymark Airlines' 'Skytrans Airlines' 'SkyUp Airlines'
 'SkyWest Airlines' 'SkyWork Airlines' 'Smartavia' 'SmartLynx Airlines'
 'SmartWings' 'Sol Líneas Aéreas' 'Solomon Airlines' 'Somon Air'
 'South African Airways' 'Southwest Airlines' 'SpiceJet' 'Spirit Airlines'
 'SriLankan Airlines' 'Sriwijaya Air' 'StarFlyer' 'Sudan Airways'
 'Sun Country Airlines' 'Sun-Air' 'Sunwing Airlines' 'Suparna Airlines'
 'Super Air Jet' 'Surinam Airways' 'SVG Air' 'Swoop' 'SyrianAir'
 "T'Way Air" 'TAAG Angola Airlines' 'TACA Regional' 'TAG Airlines'
 'Tailwind Airlines' 'TAM Airlines' 'TAME' 'Tame Línea Aérea Del Ecuador'
 'TAP Portugal' 'TAR Aerolineas' 'Thai AirAsia' 'Thai Airways'
 'Thai Lion Air' 'Thai Smile Airways' 'Thomas Cook Airlines'
 'Thomas Cook Airlines Scandinavia' 'Thomson Airways' 'Tianjin Airlines'
 'Tibet Airlines' 'Tigerair' 'Tigerair Australia' 'Tigerair Taiwan'
 'Titan Airways' 'Transaero Airlines' 'TransAsia Airways' 'Transavia'
 'TransNusa' 'Trigana Air' 'Tropic Air Belize' 'TUI Airways' 'TUIfly'
 'TUIfly Nordic' 'Tunisair' 'Turkish Airlines' 'Turkmenistan Airlines'
 'TUS Airways' 'Uganda Airlines' 'Ultra Air' 'United Airlines'
 'UP by El Al' 'Ural Airlines' 'US Airways' 'US-Bangla Airlines'
 'Utair Aviation' 'Uzbekistan Airways' 'V Air' 'Vanilla Air' 'ViaAir'
 'Vietnam Airlines' 'Virgin America' 'Virgin Australia' 'Vistara'
 'Viva Air' 'VivaAerobús' 'VivaColombia' 'VLM Airlines' 'Volaris'
 'Volotea' 'Voyage Air' 'Vueling Airlines' 'Wamos Air' 'Wideroe' 'Winair'
 'Wingo' 'Wings Air' 'Wizz Air' 'World2Fly' 'WOW air' 'Xiamen Airlines'
 'XL Airways France' 'Yakutia Airlines' 'Yangon Airways' 'Yemenia'
 'Yeti Airlines' 'Zambia Airways' 'ZIPAIR']
['9' '1' '8' '2' '3' '5' '6' '7' '4' 'n']
['"pretty decent airline"' '"Not a good airline"'
 '"flight was fortunately short"' ...
 '"$300 savings was absolutely not worth it"'
 '"It was immaculately clean"' '"lost all of our money with no refund"']
['11th November 2019' '25th June 2019' '28th September 2019' ...
 '17th November 2003' '23rd October 2003' '6th May 2003']
[ True False]
["  Moroni to Moheli. Turned out to be a pretty decent airline. Online booking worked well, checkin and boarding was fine and the plane looked well maintained. Its a very short flight - just 20 minutes or so so i didn't expect much but they still managed to hand our a bottle of water and some biscuits which i though was very nice. Both flights on time."
 ' Moroni to Anjouan. It is a very small airline. My ticket advised me to turn up at 0800hrs which I did. There was confusion at this small airport. I was then directed to the office of AB Aviation which was still closed. It opened at 0900hrs and I was told that the flight had been put back to 1300hrs and that they had tried to contact me. This could not be true as they did not have my phone number. I was with a local guide and he had not been informed either. I presume that I was bumped off. The later flight did operate but as usual, there was confusion at check-in. The flight was only 30mins and there were no further problems. Not a good airline but it is the only one for Comoros.'
 '  Anjouan to Dzaoudzi. A very small airline and the only airline based in Comoros. Check-in was disorganised because of locals with big packages and disinterested staff. The flight was fortunately short (30 mins). Took off on time and landed on time. With a short flight like there was of course no in-flight entertainment nor cabin service except for biscuits and a bottle of water, which was quite nice!'
 ...
 "  Flight was leaving at 23.15 and after an hour and a half flying had to get back to airport due to a medical emergency of a passenger. Upon landing we were left inside the plane in the tarmac until 4:15 am and told to deplane and pick up our luggage and flight would be cancelled. Zipair did not take responsibility for the passengers and just left everyone to sort themselves out at 5am, even families with small children,  their reply was “oh, there are many hotels in Bangkok”. When these situations have occurred to me always airline took to hotel, specially once we had already left ground. They didnt offer anything at all at the time… Flight was rescheduled for the next day at the same time.. upon checking in at 10pm or so, they offered a meal voucher of 300THB as compensation… couldn't they have given the voucher in the morning and not just an hour before leaving. Will not recommend to anyone"
 ' Zipair is JAL’s budget airline. They don’t have classes of travel, you just pick your seat (flat bed, emergency exit etc) and pay accordingly. We usually travel BA or JAL business class. This trip was last minute and JAL business was going to cost $8k. Instead we paid just over $2.5k to fly with Zipair in their fully flat seats. Your ticket includes nothing but 7kg of cabin baggage (and they do weigh rucksacks/handbags etc), a bottle of water and the seat you booked. Check in process was not good. Of course we aren’t used to queuing for check in, but here everyone queues. There is no Advanced Passenger Information loaded, so with covid added the check in process was long. Also both our cabin bags were over 7kg so we had to put a bag in the hold. (You can pay to add a bag to the hold, but you can’t pay for additional cabin baggage. They are strict on weight to the gram). We were also asked if we had a return ticket, which as it was booked at the same time as the outward trip was a bit worrying. Finally because the seat map is misleading we had not booked seats together (eg row 2 does not align across the cabin so although we had seats that were both in row 2, in fact I was sat behind and to the right of my husband. This was pointed out to us at check-in but we weren’t allowed to change our seats despite the fact that there were only 2 other seats taken in the fully flat cabin. Seats must be booked at least 24 hours before check-in and again this is enforced strictly. (We couldn’t even change seats on board although the seat on my husband’s left was free). The fully flat bed was nearly as good as JAL/BA business class (not quite so much storage). Includes reading light, table and some storage space. You can stow your hand baggage under the foot stool for take-off and landing (an improvement on the new BA business class seats). Its quite hard, but otherwise good. It was immaculately clean (again better than BA), cabin crew were excellent and it felt safe. There is no entertainment screen. WiFi is included free of charge, and a (very) small selection of films is available. The fully flat seat has a USB charging point. Fairly basic food and drinks can be bought on board by ordering via your mobile device and QI code. The onboard shop opens about an hour after take-off and closes about an hour before landing. Otherwise meals must be booked in advance. Pre-booked meals are served before the onboard shop is open, so you can’t buy a drink until after your meal. Cushions and blankets are not included, but can be bought from the online shop. In deciding whether to use Zipair you need to compare cost to convenience. If you have time to download movies, book seats in advance (there is no app to make this easy), pre-order meals, and to bring your own pre- and with-meal drinks that will help. Also to bring your own cushion/blanket if you like to sleep as soon as you get on board. For me, some of the joy was missing. There wasn’t enough meal/entertainment/shopping to pass much time for those who are not good at sleeping. Is that worth $5.5k - only you can answer that.'
 '  They lied about connection in Narita and we lost all of our money with no refund. They have no agreements with any connecting airlines to transfer you once in Narita, hence they denied boarding and did not offer a refund. Nor did they advise of such at purchase. Lost $1000 with this airline.']
[nan 'E120' 'Embraer E120 ' ... 'ATR 72 500' 'Jetstream J41' 'Boeing787']
['Solo Leisure' 'Couple Leisure' 'Business' 'Family Leisure' nan]
['Economy Class' 'Business Class' nan 'Premium Economy' 'First Class']
['Moroni to Moheli' 'Moroni to Anjouan' 'Anjouan to Dzaoudzi' ...
 'Tokyo Narita to Los Angeles' 'Hanoi to Los Angeles via Tokyo '
 'Los Angeles to Seoul via Tokyo Narita']
['November 2019' 'June 2019' 'September 2019' 'August 2019' 'October 2018'
 'July 2018' 'May 2018' 'June 2018' 'April 2018' 'March 2018'
 'September 2017' 'November 2017' 'October 2017' 'June 2017' 'April 2017'
 'December 2016' 'October 2016' 'November 2016' 'August 2016'
 'September 2016' 'July 2016' 'January 2016' 'September 2015'
 'February 2015' 'August 2015' nan 'July 2023' 'June 2023' 'May 2023'
 'April 2023' 'March 2023' 'September 2022' 'July 2022' 'February 2023'
 'June 2022' 'December 2022' 'January 2023' 'November 2022' 'October 2022'
 'August 2022' 'May 2022' 'April 2022' 'May 2021' 'September 2021'
 'March 2022' 'February 2022' 'December 2021' 'November 2021'
 'October 2021' 'April 2019' 'July 2017' 'January 2022' 'August 2021'
 'October 2020' 'July 2021' 'July 2020' 'April 2020' 'March 2020'
 'December 2020' 'August 2020' 'January 2020' 'February 2020'
 'December 2019' 'July 2019' 'October 2019' 'May 2019' 'January 2019'
 'March 2019' 'November 2020' 'December 2018' 'February 2019'
 'November 2018' 'February 2018' 'December 2017' 'August 2017'
 'March 2017' 'March 2016' 'February 2017' 'January 2017' 'June 2016'
 'May 2016' 'April 2016' 'May 2015' 'November 2015' 'December 2015'
 'October 2015' 'July 2015' 'January 2018' 'April 2012' 'June 2021'
 'April 2021' 'September 2020' 'May 2017' 'June 2015' 'April 2015'
 'May 2020' 'June 2020' 'September 2018' 'August 2018' 'February 2021'
 'January 2015' 'August 2014' 'March 2021' 'January 2021' 'February 2016'
 'March 2015' 'December 2014' 'November 2014' 'August 2023' 'October 2014']
[ 4.  2.  1.  3.  5. nan  0.]
[ 5.  2.  1.  4.  3. nan  0.]
[ 4.  1. nan  3.  2.  5.  0.]
[ 4.  1.  5.  3.  2. nan]
[nan  1.  4.  5.  3.  2.  0.]
[nan  1.  5.  3.  4.  2.  0.]
[ 3.  2.  1.  5.  4. nan  0.]
['yes' 'no']

In [60]:
print(df.isna().sum())

Unnamed: 0                    0
Airline Name                  0
Overall_Rating                0
Review_Title                  0
Review Date                   0
Verified                      0
Review                        0
Aircraft                  16042
Type Of Traveller          3738
Seat Type                  1096
Route                      3828
Date Flown                 3754
Seat Comfort               4155
Cabin Staff Service        4260
Food & Beverages           8671
Ground Service             4793
Inflight Entertainment    12342
Wifi & Connectivity       17251
Value For Money            1066
Recommended                   0
dtype: int64

In [61]:
df.loc[df["Overall_Rating"] == 'n', "Overall_Rating"] = -1

df.loc[df["Verified"] == True, "Verified"] = "true"
df.loc[df["Verified"] == False, "Verified"] = "false"

df.loc[df["Recommended"] == 'yes', "Recommended"] = "true"
df.loc[df["Recommended"] == 'no', "Recommended"] = "false"

for c in ["Aircraft", "Seat Type", "Route", "Type Of Traveller", "Date Flown"]:
  df[c].fillna("Unknown", inplace =True)

for n in ["Seat Comfort", "Cabin Staff Service", "Food & Beverages", "Wifi & Connectivity", "Ground Service", "Inflight Entertainment", "Value For Money"]:
  df[n].fillna(-1, inplace =True)

<ipython-input-61-9f655beda998>:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'true' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df.loc[df["Verified"] == True, "Verified"] = "true"
<ipython-input-61-9f655beda998>:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[c].fillna("Unknown", inplace =True)
<ipython-input-61-9f655beda998>:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[n].fillna(-1, inplace =True)

In [62]:
t = df.columns
for e in t:
  print(df[e].unique())

[    0     1     2 ... 23168 23169 23170]
['AB Aviation' 'Adria Airways' 'Aegean Airlines' 'Aer Lingus' 'Aero VIP'
 'Aerocaribbean' 'Aeroflot Russian Airlines' 'AeroItalia'
 'Aerolineas Argentinas' 'Aeromar' 'Aeromexico' 'Aerosur'
 'Africa World Airlines' 'Afriqiyah Airways' 'Aigle Azur' 'Air Algerie'
 'Air Antilles' 'Air Arabia' 'Air Astana' 'Air Austral' 'Air Bagan'
 'Air Berlin' 'Air Botswana' 'Air Burkina' 'Air Busan' 'Air Cairo'
 'Air Canada' 'Air Canada rouge' 'Air Caraibes' 'Air China' 'Air Corsica'
 'Air Costa' "Air Cote d'Ivoire" 'Air Djibouti' 'Air Dolomiti'
 'Air Europa' 'Air France' 'Air Greenland' 'Air Iceland Connect'
 'Air India' 'Air India Express' 'Air Italy' 'Air Juan' 'Air KBZ'
 'Air Koryo' 'Air Labrador' 'Air Macau' 'Air Madagascar' 'Air Malawi'
 'Air Malta' 'Air Mauritius' 'Air Mediterranee' 'Air Memphis'
 'Air Moldova' 'Air Namibia' 'Air New Zealand' 'Air Niugini'
 "Air North Yukon's Airline" 'Air Nostrum' 'Air Panama' 'Air Pegasus'
 'Air Rarotonga' 'Air Serbia' 'Air Seychelles' 'Air Tahiti Nui'
 'Air Tanzania' 'Air Transat' 'Air Zimbabwe' 'AirAsia' 'AirAsia India'
 'AirAsia Philippines' 'AirAsia X' 'AirAsia Zest' 'airBaltic' 'Aircalin'
 'Airlink' 'Airnorth' 'AirSWIFT' 'Akasa Air' 'Alaska Airlines' 'Alitalia'
 'Allegiant Air' 'Alliance Air' 'Alliance Airlines' 'Amaszonas'
 'American Airlines' 'American Eagle' 'ANA All Nippon Airways'
 'AnadoluJet' 'Andes Líneas Aéreas' 'Ariana Afghan Airlines' 'Arik Air'
 'Arkefly' 'Armenia Air Company' 'Asiana Airlines' 'ASKY Airlines'
 'ATA Airlines' 'Atlantic Airways' 'Auric Air' 'Aurigny Air'
 'Austrian Airlines' 'Avelo Airlines' 'Avianca' 'Avior Airlines'
 'Azerbaijan Airlines' 'Azur Air Germany' 'BA CityFlyer' 'Badr Airlines'
 'Bahamasair' 'Bamboo Airways' 'Bangkok Airways' 'Bassaka Air' 'Batik Air'
 'Beijing Capital Airlines' 'Belavia' 'Berjaya Air' 'Bhutan Airlines'
 'Binter Canarias' 'Blue Air' 'Blue Islands' 'Blue Panorama Airlines'
 'Blue1' 'Bluebird Airways' 'bmi Regional' 'BoraJet' 'Boutique Air'
 'Breeze Airways' 'British Airways' 'Brussels Airlines' 'Buddha Air'
 'Bulgaria Air' 'Buta Airways' 'Camair-Co' 'Cambodia Airways'
 'Cambodia Bayon Airlines' 'Canadian North' 'Canaryfly' 'Cape Air'
 'Caribbean Airlines' 'Carpatair' 'Cathay Dragon' 'Cathay Pacific Airways'
 'Cayman Airways' 'Cebu Pacific' 'CemAir' 'Central Mountain Air'
 'China Airlines' 'China Eastern Airlines' 'China Southern Airlines'
 'China United Airlines' 'Citilink' 'CityJet' 'Coastal Aviation' 'Cobalt'
 'Comair' 'Condor Airlines' 'Conviasa' 'Copa Airlines' 'Corendon Airlines'
 'Corsair' 'Croatia Airlines' 'CSA Czech Airlines' 'Cubana Airlines'
 'Cyprus Airways' 'Delta Air Lines' 'Dimonim Air' 'Dniproavia' 'Dragonair'
 'Druk Air' 'Dynamic International Airways' 'Eastern Airlines'
 'Eastern Airways' 'Easyfly' 'easyJet' 'Edelweiss Air' 'Egyptair'
 'El Al Israel Airlines' 'Ellinair' 'Emirates' 'Eritrean Airlines'
 'Ernest Airlines' 'Estonian Air' 'Eswatini Air' 'Ethiopian Airlines'
 'Etihad Airways' 'euroAtlantic Airways' 'Europe Airpost' 'Eurowings'
 'EVA Air' 'Evelop Airlines' 'EWA Air' 'Ravn Alaska' 'fastjet'
 'Felix Airways' 'Fiji Airways' 'Finnair' 'Firefly' 'Flair Airlines'
 'Fly540.com' 'flyadeal' 'FlyArystan' 'flybe' 'flydubai' 'Flynas' 'FLYONE'
 'FlySafair' 'FMI Air' 'French Bee' 'Frontier Airlines' 'Garuda Indonesia'
 'Georgian Airways' 'Germania Airline' 'Germanwings' 'Go First' 'GoAir'
 'Golden Myanmar Airlines' 'Grand Cru Airlines' 'Greater Bay Airlines'
 'Gulf Air' 'Hainan Airlines' 'Hawaiian Airlines' 'Henan Airlines'
 'Hi Fly' 'Himalaya Airlines' 'HiSky' 'Hong Kong Airlines' 'HOP!'
 'Horizon Air' 'Hunnu Air' 'Iberia' 'Iberia Express' 'Iberojet'
 'Icelandair' 'Insel Air' 'Intercaribbean Airways' 'Interjet' 'InterSky'
 'Iran Air' 'Iraqi Airways' 'Israir Airlines' 'ITA Airways'
 'Japan Airlines' 'Jazeera Airways' 'Jazz' 'JC International Airlines'
 'Jeju Air' 'Jet Airways' 'Jet2.com' 'Jetairfly' 'Jetblue Airways'
 'JetSmart' 'Jetstar Airways' 'Jetstar Asia' 'Jetstar Japan'
 'Jetstar Pacific' 'JetsuiteX' 'Jin Air' 'Joon' 'Jordan Aviation'
 'Kam Air' 'Kan Air' 'Karthago Airlines' 'KD Air' 'Kenya Airways'
 'KLM Royal Dutch Airlines' 'Korean Air' 'Kulula' 'Kuwait Airways'
 'La Compagnie' 'LAN Airlines' 'LAN Colombia' 'LAN Peru' 'Lao Airlines'
 'LATAM Airlines' 'Laudamotion' 'LC Perú' 'Level' 'LIAT' 'Libyan Airlines'
 'Lion Air' 'Loch Lomond Seaplanes' 'Loganair' 'LOT Polish Airlines'
 'Lubeck Air' 'Lucky Air' 'Lufthansa' 'Luxair' 'Lynx Air' 'Mack Air'
 'Madagasikara Airways' 'Mahan Air' 'Malawian Airlines'
 'Malaysia Airlines' 'Maldivian' 'Malindo Air' 'Mandarin Airlines'
 'Mann Yadanarpon Airlines' 'Manta Air' 'Martinair' 'Mauritania Airlines'
 'Maya Island Air' 'MAYAir' 'MEGA Maldives Airlines' 'Meridiana'
 'Mihin Lanka' 'Mokulele Airlines' 'Moldavian Airlines' 'Monarch Airlines'
 'Montenegro Airlines' 'Motor Sich Airlines' 'Myanmar Airways'
 'Myanmar National Airlines' 'NAM Air' 'Nature Air' 'Nauru Airlines'
 'Nepal Airlines' 'NextJet' 'NIKI' 'Nile Air' 'Nok Air' 'NokScoot'
 'Nordavia' 'Nordic Regional Airlines' 'Nordica' 'NordStar'
 'Nordwind Airlines' 'Norse Atlantic Airways' 'Norwegian' 'Nouvelair'
 'Novair' 'Novoair' 'Okay Airways' 'Olympic Air' 'Oman Air'
 'Omni Air International' 'Onur Air' 'Openskies' 'Pacific Airlines'
 'PAL Express' 'Pan Pacific Airlines' 'Passion Air' 'PAWA Dominicana'
 'Peach Aviation' 'Pegasus Airlines' 'PenAir' 'Peruvian Airlines'
 'Petroleum Air Services' 'Philippine Airlines' 'Phuket Air' 'PLAY'
 'Pobeda Airlines' 'Porter Airlines' 'Primera Air' 'Privilege Style'
 'Qantas Airways' 'QantasLink' 'Qatar Airways' 'Qazaq Air'
 'Red Wings Airlines' 'Regent Airways' 'Regional Express' 'Rex Airlines'
 'Rhein-Neckar Air' 'Rossiya Airlines' 'Royal Air Maroc'
 'Royal Brunei Airlines' 'Royal Jordanian Airlines' 'Rwandair' 'Ryanair'
 'S7 Siberia Airlines' 'SA Express' 'Safarilink' 'Safi Airways'
 'Salam Air' 'Sansa Airlines' 'SATA Air Azores' 'SATENA'
 'Saudi Arabian Airlines' 'SCAT Airlines' 'Scoot' 'Seaborne Airlines'
 'SereneAir' 'Shaheen Air' 'Shandong Airlines' 'Shanghai Airlines'
 'Shenzhen Airlines' 'Sichuan Airlines' 'SilkAir' 'Silver Airways'
 'Singapore Airlines' 'Sky Airline' 'Sky Express Airlines' 'Skybus'
 'Skymark Airlines' 'Skytrans Airlines' 'SkyUp Airlines'
 'SkyWest Airlines' 'SkyWork Airlines' 'Smartavia' 'SmartLynx Airlines'
 'SmartWings' 'Sol Líneas Aéreas' 'Solomon Airlines' 'Somon Air'
 'South African Airways' 'Southwest Airlines' 'SpiceJet' 'Spirit Airlines'
 'SriLankan Airlines' 'Sriwijaya Air' 'StarFlyer' 'Sudan Airways'
 'Sun Country Airlines' 'Sun-Air' 'Sunwing Airlines' 'Suparna Airlines'
 'Super Air Jet' 'Surinam Airways' 'SVG Air' 'Swoop' 'SyrianAir'
 "T'Way Air" 'TAAG Angola Airlines' 'TACA Regional' 'TAG Airlines'
 'Tailwind Airlines' 'TAM Airlines' 'TAME' 'Tame Línea Aérea Del Ecuador'
 'TAP Portugal' 'TAR Aerolineas' 'Thai AirAsia' 'Thai Airways'
 'Thai Lion Air' 'Thai Smile Airways' 'Thomas Cook Airlines'
 'Thomas Cook Airlines Scandinavia' 'Thomson Airways' 'Tianjin Airlines'
 'Tibet Airlines' 'Tigerair' 'Tigerair Australia' 'Tigerair Taiwan'
 'Titan Airways' 'Transaero Airlines' 'TransAsia Airways' 'Transavia'
 'TransNusa' 'Trigana Air' 'Tropic Air Belize' 'TUI Airways' 'TUIfly'
 'TUIfly Nordic' 'Tunisair' 'Turkish Airlines' 'Turkmenistan Airlines'
 'TUS Airways' 'Uganda Airlines' 'Ultra Air' 'United Airlines'
 'UP by El Al' 'Ural Airlines' 'US Airways' 'US-Bangla Airlines'
 'Utair Aviation' 'Uzbekistan Airways' 'V Air' 'Vanilla Air' 'ViaAir'
 'Vietnam Airlines' 'Virgin America' 'Virgin Australia' 'Vistara'
 'Viva Air' 'VivaAerobús' 'VivaColombia' 'VLM Airlines' 'Volaris'
 'Volotea' 'Voyage Air' 'Vueling Airlines' 'Wamos Air' 'Wideroe' 'Winair'
 'Wingo' 'Wings Air' 'Wizz Air' 'World2Fly' 'WOW air' 'Xiamen Airlines'
 'XL Airways France' 'Yakutia Airlines' 'Yangon Airways' 'Yemenia'
 'Yeti Airlines' 'Zambia Airways' 'ZIPAIR']
['9' '1' '8' '2' '3' '5' '6' '7' '4' -1]
['"pretty decent airline"' '"Not a good airline"'
 '"flight was fortunately short"' ...
 '"$300 savings was absolutely not worth it"'
 '"It was immaculately clean"' '"lost all of our money with no refund"']
['11th November 2019' '25th June 2019' '28th September 2019' ...
 '17th November 2003' '23rd October 2003' '6th May 2003']
['true' 'false']
["  Moroni to Moheli. Turned out to be a pretty decent airline. Online booking worked well, checkin and boarding was fine and the plane looked well maintained. Its a very short flight - just 20 minutes or so so i didn't expect much but they still managed to hand our a bottle of water and some biscuits which i though was very nice. Both flights on time."
 ' Moroni to Anjouan. It is a very small airline. My ticket advised me to turn up at 0800hrs which I did. There was confusion at this small airport. I was then directed to the office of AB Aviation which was still closed. It opened at 0900hrs and I was told that the flight had been put back to 1300hrs and that they had tried to contact me. This could not be true as they did not have my phone number. I was with a local guide and he had not been informed either. I presume that I was bumped off. The later flight did operate but as usual, there was confusion at check-in. The flight was only 30mins and there were no further problems. Not a good airline but it is the only one for Comoros.'
 '  Anjouan to Dzaoudzi. A very small airline and the only airline based in Comoros. Check-in was disorganised because of locals with big packages and disinterested staff. The flight was fortunately short (30 mins). Took off on time and landed on time. With a short flight like there was of course no in-flight entertainment nor cabin service except for biscuits and a bottle of water, which was quite nice!'
 ...
 "  Flight was leaving at 23.15 and after an hour and a half flying had to get back to airport due to a medical emergency of a passenger. Upon landing we were left inside the plane in the tarmac until 4:15 am and told to deplane and pick up our luggage and flight would be cancelled. Zipair did not take responsibility for the passengers and just left everyone to sort themselves out at 5am, even families with small children,  their reply was “oh, there are many hotels in Bangkok”. When these situations have occurred to me always airline took to hotel, specially once we had already left ground. They didnt offer anything at all at the time… Flight was rescheduled for the next day at the same time.. upon checking in at 10pm or so, they offered a meal voucher of 300THB as compensation… couldn't they have given the voucher in the morning and not just an hour before leaving. Will not recommend to anyone"
 ' Zipair is JAL’s budget airline. They don’t have classes of travel, you just pick your seat (flat bed, emergency exit etc) and pay accordingly. We usually travel BA or JAL business class. This trip was last minute and JAL business was going to cost $8k. Instead we paid just over $2.5k to fly with Zipair in their fully flat seats. Your ticket includes nothing but 7kg of cabin baggage (and they do weigh rucksacks/handbags etc), a bottle of water and the seat you booked. Check in process was not good. Of course we aren’t used to queuing for check in, but here everyone queues. There is no Advanced Passenger Information loaded, so with covid added the check in process was long. Also both our cabin bags were over 7kg so we had to put a bag in the hold. (You can pay to add a bag to the hold, but you can’t pay for additional cabin baggage. They are strict on weight to the gram). We were also asked if we had a return ticket, which as it was booked at the same time as the outward trip was a bit worrying. Finally because the seat map is misleading we had not booked seats together (eg row 2 does not align across the cabin so although we had seats that were both in row 2, in fact I was sat behind and to the right of my husband. This was pointed out to us at check-in but we weren’t allowed to change our seats despite the fact that there were only 2 other seats taken in the fully flat cabin. Seats must be booked at least 24 hours before check-in and again this is enforced strictly. (We couldn’t even change seats on board although the seat on my husband’s left was free). The fully flat bed was nearly as good as JAL/BA business class (not quite so much storage). Includes reading light, table and some storage space. You can stow your hand baggage under the foot stool for take-off and landing (an improvement on the new BA business class seats). Its quite hard, but otherwise good. It was immaculately clean (again better than BA), cabin crew were excellent and it felt safe. There is no entertainment screen. WiFi is included free of charge, and a (very) small selection of films is available. The fully flat seat has a USB charging point. Fairly basic food and drinks can be bought on board by ordering via your mobile device and QI code. The onboard shop opens about an hour after take-off and closes about an hour before landing. Otherwise meals must be booked in advance. Pre-booked meals are served before the onboard shop is open, so you can’t buy a drink until after your meal. Cushions and blankets are not included, but can be bought from the online shop. In deciding whether to use Zipair you need to compare cost to convenience. If you have time to download movies, book seats in advance (there is no app to make this easy), pre-order meals, and to bring your own pre- and with-meal drinks that will help. Also to bring your own cushion/blanket if you like to sleep as soon as you get on board. For me, some of the joy was missing. There wasn’t enough meal/entertainment/shopping to pass much time for those who are not good at sleeping. Is that worth $5.5k - only you can answer that.'
 '  They lied about connection in Narita and we lost all of our money with no refund. They have no agreements with any connecting airlines to transfer you once in Narita, hence they denied boarding and did not offer a refund. Nor did they advise of such at purchase. Lost $1000 with this airline.']
['Unknown' 'E120' 'Embraer E120 ' ... 'ATR 72 500' 'Jetstream J41'
 'Boeing787']
['Solo Leisure' 'Couple Leisure' 'Business' 'Family Leisure' 'Unknown']
['Economy Class' 'Business Class' 'Unknown' 'Premium Economy'
 'First Class']
['Moroni to Moheli' 'Moroni to Anjouan' 'Anjouan to Dzaoudzi' ...
 'Tokyo Narita to Los Angeles' 'Hanoi to Los Angeles via Tokyo '
 'Los Angeles to Seoul via Tokyo Narita']
['November 2019' 'June 2019' 'September 2019' 'August 2019' 'October 2018'
 'July 2018' 'May 2018' 'June 2018' 'April 2018' 'March 2018'
 'September 2017' 'November 2017' 'October 2017' 'June 2017' 'April 2017'
 'December 2016' 'October 2016' 'November 2016' 'August 2016'
 'September 2016' 'July 2016' 'January 2016' 'September 2015'
 'February 2015' 'August 2015' 'Unknown' 'July 2023' 'June 2023'
 'May 2023' 'April 2023' 'March 2023' 'September 2022' 'July 2022'
 'February 2023' 'June 2022' 'December 2022' 'January 2023'
 'November 2022' 'October 2022' 'August 2022' 'May 2022' 'April 2022'
 'May 2021' 'September 2021' 'March 2022' 'February 2022' 'December 2021'
 'November 2021' 'October 2021' 'April 2019' 'July 2017' 'January 2022'
 'August 2021' 'October 2020' 'July 2021' 'July 2020' 'April 2020'
 'March 2020' 'December 2020' 'August 2020' 'January 2020' 'February 2020'
 'December 2019' 'July 2019' 'October 2019' 'May 2019' 'January 2019'
 'March 2019' 'November 2020' 'December 2018' 'February 2019'
 'November 2018' 'February 2018' 'December 2017' 'August 2017'
 'March 2017' 'March 2016' 'February 2017' 'January 2017' 'June 2016'
 'May 2016' 'April 2016' 'May 2015' 'November 2015' 'December 2015'
 'October 2015' 'July 2015' 'January 2018' 'April 2012' 'June 2021'
 'April 2021' 'September 2020' 'May 2017' 'June 2015' 'April 2015'
 'May 2020' 'June 2020' 'September 2018' 'August 2018' 'February 2021'
 'January 2015' 'August 2014' 'March 2021' 'January 2021' 'February 2016'
 'March 2015' 'December 2014' 'November 2014' 'August 2023' 'October 2014']
[ 4.  2.  1.  3.  5. -1.  0.]
[ 5.  2.  1.  4.  3. -1.  0.]
[ 4.  1. -1.  3.  2.  5.  0.]
[ 4.  1.  5.  3.  2. -1.]
[-1.  1.  4.  5.  3.  2.  0.]
[-1.  1.  5.  3.  4.  2.  0.]
[ 3.  2.  1.  5.  4. -1.  0.]
['true' 'false']

In [63]:
print(df.isna().sum())

Unnamed: 0                0
Airline Name              0
Overall_Rating            0
Review_Title              0
Review Date               0
Verified                  0
Review                    0
Aircraft                  0
Type Of Traveller         0
Seat Type                 0
Route                     0
Date Flown                0
Seat Comfort              0
Cabin Staff Service       0
Food & Beverages          0
Ground Service            0
Inflight Entertainment    0
Wifi & Connectivity       0
Value For Money           0
Recommended               0
dtype: int64

In [64]:
df["Review Date"] = pd.to_datetime(df["Review Date"], format="%dth %B %Y", errors="coerce")

In [65]:
df.isnull().sum()

Unnamed: 0                   0
Airline Name                 0
Overall_Rating               0
Review_Title                 0
Review Date               5113
Verified                     0
Review                       0
Aircraft                     0
Type Of Traveller            0
Seat Type                    0
Route                        0
Date Flown                   0
Seat Comfort                 0
Cabin Staff Service          0
Food & Beverages             0
Ground Service               0
Inflight Entertainment       0
Wifi & Connectivity          0
Value For Money              0
Recommended                  0
dtype: int64

In [66]:
df.dtypes
df['Review Date']

0       2019-11-11
1       2019-06-25
2       2019-06-25
3       2019-09-28
4       2019-09-24
           ...
23166   2022-07-05
23167          NaT
23168          NaT
23169          NaT
23170   2022-05-20
Name: Review Date, Length: 23171, dtype: datetime64[ns]

In [67]:
df.rename(columns={'Unnamed: 0': 'Review Id'}, inplace=True)

In [68]:
df.to_csv("airlines.csv", index=False)